use universityclb;

CREATE TABLE IF NOT EXISTS FACULTY
(
 FID CHAR(8),
 LastName VARCHAR(20) NOT NULL,
 FirstName VARCHAR(20) NOT NULL,
 FacRank CHAR(4),
 Tenured CHAR(1),
 DeptID CHAR(4),
 PRIMARY KEY (FID),
 FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DID)
);

CREATE TABLE IF NOT EXISTS STUDENT
(
 STID CHAR(8),
 LastName VARCHAR(20) NOT NULL,
 FirstName VARCHAR(20) NOT NULL,
 Major CHAR(4),
 StLevel CHAR(2),
 GPA DECIMAL(4,3),
 AdvisorID CHAR(8),
 PRIMARY KEY (STID),
 FOREIGN KEY (AdvisorID) REFERENCES FACULTY(FID)
);

CREATE TABLE IF NOT EXISTS Course
(
 CID CHAR(8),
 Dept CHAR(4),
 Title VARCHAR(50),
 Credits SMALLINT,
 PRIMARY KEY (CID),
 FOREIGN KEY (Dept) REFERENCES DEPARTMENT(DID)
);

CREATE TABLE IF NOT EXISTS Section
(
 SectID CHAR(6),
 CourseID CHAR(8) NOT NULL,
 SectionNumber CHAR(3) NOT NULL,
 Semester CHAR(4) NOT NULL,
 Yr CHAR(4) NOT NULL,
 InstructorID CHAR(8)
 )